### ISSUE TITLE
here we need a link change

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#174]
https://github.com/MobileTeleSystems/onetl/blob/0d044667037547b767630e870e9b6739caba0a60/onetl/connection/db_connection/mysql/connection.py#L96

mysql j connector docs structure changed, article address need to be updated to https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html

**Comment by dolfinus** [comment]
Fixed.
