### ISSUE TITLE
for a most latest microsoft doc version link needs to be changed 

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#175]
https://github.com/MobileTeleSystems/onetl/blob/11dec83e4e06da5290b9bc182113a94247103dbb/onetl/connection/db_connection/mssql/connection.py#L97

to https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties#properties

**Comment by dolfinus** [comment]
Done
