### ISSUE TITLE
extra options for oracle connection source

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#176]
https://github.com/MobileTeleSystems/onetl/blob/11dec83e4e06da5290b9bc182113a94247103dbb/onetl/connection/db_connection/oracle/connection.py#L147

it seems that one of this pages is better candidate for extra connection properties: https://docs.oracle.com/en/database/oracle/oracle-database/23/jajdb/oracle/jdbc/OracleConnection.html
https://docs.oracle.com/en/database/oracle/oracle-database/23/jajdb/oracle/jdbc/OracleDriver.html

**Comment by dolfinus** [comment]
Done
