### ISSUE TITLE
recreate_entire_table || replace_entire_table?

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#220]
https://github.com/MobileTeleSystems/onetl/blob/d2536b677bd0c363bfb8b8f4adb485d5c6f0c519/onetl/connection/db_connection/hive/options.py#L209

it seems that `recreate_entire_table` need to be replaced with  `replace_entire_table`

**Comment by dolfinus** [comment]
Fixed
