### ISSUE TITLE
override KafkaReadOptions

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#223]
https://github.com/MobileTeleSystems/onetl/blob/6849b4640eae8cf46d5a8d9df59f2cfedafe97c8/onetl/connection/db_connection/kafka/options.py#L74

it seems that
'and cannot be overridden by the user in ``KafkaReadOptions``  class to avoid issues.'
will be more clear than
'and cannot be set in ``KafkaReadOptions`` class and be overridden by the user to avoid issues.'

**Comment by dolfinus** [comment]
Fixed
