### ISSUE TITLE
monogdb docs restructured 2

### ISSUE THREAD

**Issue by wm-wm-wm** [MobileTeleSystems/onetl#225]
https://github.com/MobileTeleSystems/onetl/blob/6849b4640eae8cf46d5a8d9df59f2cfedafe97c8/onetl/connection/db_connection/mongodb/options.py#L133

it seems that mongodb docs restructured and right now link `https://www.mongodb.com/docs/spark-connector/current/configuration/read` redirects to `https://www.mongodb.com/docs/spark-connector/current/batch-mode/batch-read-config/`

**Comment by dolfinus** [comment]
Fixed
