### ISSUE TITLE
pytest: command not found

### ISSUE THREAD

**Issue by Capas0** [MobileTeleSystems/onetl#37]
I followed the instructions provided in the README file to run the tests. When attempting to execute `docker-compose run --rm onetl ./run_tests.sh`, I receive the following error message: `"/app/pytest_runner.sh: line 15: pytest: command not found"`

I also noticed that running the command `docker-compose run --rm onetl bash -c 'pip freeze | wc -l'` outputs 0. This indicates that there are no pip packages installed within the container.

However, if I remove the volume specified in the [docker-compose.yml file](https://github.com/MobileTeleSystems/onetl/blob/0832de1adb1bfce5f84569126aad9467f36517b3/docker-compose.yml#L15), the pip packages become visible within the container, but the onetl files are no longer accessible.

I would appreciate any assistance or guidance in resolving this issue. Thank you!

**Comment by dolfinus** [comment]
Hi.

Should be fixed in #38

**Comment by dolfinus** [comment]
Please check

**Comment by Capas0** [comment]
Problem solved. Thank you!
